### ISSUE TITLE
Send not working

### ISSUE THREAD

**Issue by haustraliaer** [hivewallet/hive-ios#10]
Pretty big one ay...

Might be due to the proxy, or CORS setup on heroku... Will need to switch over to the main web.hivewallet.com server anyway, so I'll try that first.

Error I'm getting currently in xcode is:

```
2014-07-24 11:31:55.324 Hive[21808:60b] ERROR: Cannot POST /?url=https%3A%2F%2Fbtc.blockr.io%2Fapi%2Fv1%2Ftx%2Fpush
```

**Comment by weilu** [comment]
The proxy I provided for testing has the most open CORS policy, so if it doesn't work with that, it's not going to work with production proxy. Judging from the error it doesn't seem like the proxy url is set properly as a environment variable.
