### ISSUE TITLE
Waggle not working

### ISSUE THREAD

**Issue by haustraliaer** [hivewallet/hive-ios#11]
Also a big one. 

Current error: Modal pops up with Request timeout - please check your internet connection.

No console error that I can see.

Pretty sure these three issues are gonna be related: https://github.com/hivewallet/hive-ios/issues/10, https://github.com/hivewallet/hive-ios/issues/7, https://github.com/hivewallet/hive-ios/issues/13

**Comment by weilu** [comment]
Does waggle work on hive-js?

**Comment by haustraliaer** [comment]
Yeah this is specifically an ios issue.

**Comment by haustraliaer** [comment]
Waggle loads now but won't find anyone - we should test this on production because afaik waggle still has some issues on the heroku server.

**Comment by weilu** [comment]
Heroku server has the latest waggle that prod is going to get this Friday. So if waggle doesn't work on staging, it won't on prod. 

I noticed that the geo location returned by simulator is off for me. So try testing with 2 actual devices next to each other

**Comment by haustraliaer** [comment]
Ah, absolutely correct - it was the simulator causing the issue.
