### ISSUE TITLE
Ui folds in on itself when inputs are selected

### ISSUE THREAD

**Issue by haustraliaer** [hivewallet/hive-ios#12]
Seems to happen quite randomly, the web view is getting confused about it's height when the keyboard pops up, and anything fixed position will move accordingly...

![foldingui](https://cloud.githubusercontent.com/assets/1561116/3682971/8c4c9484-12d9-11e4-8c27-86b6e6271b11.png)

aka:

![kemp](https://cloud.githubusercontent.com/assets/1561116/3682973/90e55b3e-12d9-11e4-80aa-fb63795a60d1.jpg)

**Comment by jenbennings** [comment]
![](http://i.imgur.com/e3Balgc.gif)

**Comment by haustraliaer** [comment]
After some more testing I'm fairly confident this is a simulator bug - if you click _slowly_ enough it will not happen. I've tried tapping, swipe tapping and hold and release on the actual device and can't seem to replicate. If it comes up again on _actual devices_ I'll look into hijacking the touch event or something.

**Comment by haustraliaer** [comment]
Kempfolds fixed with https://github.com/hivewallet/hive-ios/commit/d84b45ad7168!

**Comment by haustraliaer** [comment]
![fixedfold](http://weknowgifs.com/wp-content/uploads/2013/08/face-folding-no-nose-gifs-5.gif)

**Comment by mackuba** [comment]
:D
