### ISSUE TITLE
Can't switch tokens

### ISSUE THREAD

**Issue by haustraliaer** [hivewallet/hive-ios#13]
Another one for the network issue group.

Error in console:

```
2014-07-24 12:37:25.401 Hive[21877:60b] Failed to load webpage with error: Could not connect to the server.
```

**Comment by haustraliaer** [comment]
Still broken - but now loads a 404 page (when trying to switch in the cordova app).

**Comment by weilu** [comment]
I cannot reproduce your 404 error. Referenced PR with the mentioned commit from hive-js produces a working token switching feature for me. @haustraliaer can you merge hive-js master into hive-ios master then I'll rebase my PR and try to reproduce your error again?

**Comment by haustraliaer** [comment]
Seems fixed after merges from upstream.
