### ISSUE TITLE
Avatar won't update until full app/page refresh

### ISSUE THREAD

**Issue by haustraliaer** [hivewallet/hive-ios#18]
Spillover from https://github.com/hivewallet/hive-ios/issues/7

When I either add a gravatar email, or remove it - the app doesn't change my picture until a full refresh. So it appears to save it - but the view code doesn't change the image on submission. Inspecting in safari reveals: 

```
[Error] failed to replicate changes to server PouchError
    (anonymous function) (console-via-logger.js, line 173)
    (anonymous function) (application.js, line 460)
    (anonymous function) (application.js, line 724)
    (anonymous function) (application.js, line 766)
    drainQueue (application.js, line 768)
```

**Comment by weilu** [comment]
I can only reproduce the same error when I have mismatching DB_HOST and HOST (for example, HOST is set to web.hivewallet.com while DB_HOST is pointing to staging db or visa versa) in the script build step. Fixing the env vars should fix this.

**Comment by BryceTheCoder** [comment]
Test
