### ISSUE TITLE
Layout goes crazy when clicking the fiat currency selector

### ISSUE THREAD

**Issue by mackuba** [hivewallet/hive-ios#24]

**Comment by mackuba** [comment]
![image](https://cloud.githubusercontent.com/assets/28465/3763088/7252d8de-189e-11e4-94a2-81870ce84484.jpg)

**Comment by jenbennings** [comment]
See #12.

Are you using simulator?

**Comment by mackuba** [comment]
Lol, I love that gif :D 

No, on the device, on the newest build.

**Comment by jenbennings** [comment]
Sigh... Alright, I'll close this one and re-open the previous one.
