### ISSUE TITLE
Crashes on jailbroken devices

### ISSUE THREAD

**Issue by dnivi3** [hivewallet/hive-ios#33]
I jailbreak my iOS-devices and I am constantly experiencing crashes when attempting to launch Hive Wallet. I have managed to set up a wallet when booting into Substrate Safe Mode (a mode that disables code injection by Cydia Substrate), but I am unable to open Hive Wallet while in non-Safe Mode. More specifically, whenever I open the Hive app and attempt to open my wallet via the 4-digit PIN, Hive crashes immediately.

The crash logs, syslog, package list and Hive Wallet settings are available on the following link: https://www.dropbox.com/sh/mlrlvwtqjgzis1b/AAD2reWVQvkxKiR8XSg5RGE_a?dl=0

**Comment by genecyber** [comment]
Which os version and jailbreak? I'm working on a few JB devices and no crashes here.

**Comment by dnivi3** [comment]
iPhone 5S, 7.0.6. There might a conflict with other tweaks I have installed, but [CrashReporter](https://github.com/ashikase/CrashReporter), which symbolicates crash logs, showed no conflict. It would be great to receive some guidance on how to interpret the crash log and sylog I have supplied above.

According to the [symbolicated crash log](https://www.dropbox.com/sh/mlrlvwtqjgzis1b/AAC3elgEuGIrsApoaQjOvk8ha/Hive_2014-09-08-013419.symbolicated.plist?dl=1) this is what crashed:

``` C++
Exception Type:      EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype:   KERN_INVALID_ADDRESS at 0x0000000046e8beb8
Triggered by Thread: 0

Thread 0 Crashed:
0       libobjc.A.dylib                 0x1995f79d0 0x1995f0000 + 0x79d0    // _objc_msgSend + 0x10
1       UIKit                           0x19059ad84 0x190540000 + 0x5ad84   // -[UIKeyboardImpl handleObserverCallback] + 0x54
```

**Comment by ghost** [comment]
Closing as low priority issue; we can come back to it later with Hive 2.0.
