### ISSUE TITLE
When will you add Dogecoin ?

### ISSUE THREAD

**Issue by Kirvx** [hivewallet/hive-ios#34]
Hi :)

When will you add Dogecoin ?
Is that expected?

Thanks :)

**Comment by weilu** [comment]
Yes, at some point. Current hive-js API/network part of the code has gone through a major refactoring. There's still some pending issues over at upstream libraries. Once that's sorted, we'll then need to find an API provider, wrap their API with the common-blockchain interfaces (something like: https://github.com/dcousens/cb-helloblock), followed minor integration with hive-js, and lastly pull in the changes into hive-ios

**Comment by Kirvx** [comment]
Ok thanks :)
