### ISSUE TITLE
Can't Switch To Litecoin Token

### ISSUE THREAD

**Issue by kevin-morton** [hivewallet/hive-ios#38]
Hey guys, just got the app on iPhone 5s but I can't seem to go to the Litecoin portion of it. I click on Litecoin, enter my PIN, and after about 5 seconds of "Validating PIN" I get a "Whoops! Request timeout" error. If I close that it still has a spinning "Validating PIN" that makes it seem like it was only a temporary issue and it will still get there. But leaving the phone like that for 20 minutes still leaves me on that same screen. I tried it about 5 times and each time the error was exactly the same.

My internet connection is fine. I'm on WiFi at the time of this issue and can easily navigate the web and other apps no problem. Hive app while switching tokens is just timing out. Maybe it's the Hive network?

**Comment by ghost** [comment]
Thanks for the report Kevin. CC: @genecyber @weilu @tgerring have you guys noticed any issues with API connections?

**Comment by weilu** [comment]
The cert has been renewed.
