### ISSUE TITLE
iOS specific UI improvements

### ISSUE THREAD

**Issue by jenbennings** [hivewallet/hive-ios#4]
- [x] Fixed header & footer
- [x] Overlay navigation bar

**Comment by jenbennings** [comment]
- [ ] Sidebar scrolling issues

**Comment by haustraliaer** [comment]
- [x] When drawer is open, new positioning of content panels breaks sidebar click

![ios](https://cloud.githubusercontent.com/assets/1561116/3639329/37fd4dfa-1078-11e4-855f-e6f963fe6211.gif)
