### ISSUE TITLE
Build iOS and Android from the same Cordova config file

### ISSUE THREAD

**Issue by javgh** [hivewallet/hive-ios#42]
Currently the Android branch uses a slightly modified config file for Cordova, in order to set a different app id. It would be nice to unify this back into one general file.

Originally the id `com.hivewallet.Hive.iOS` has been picked. In theory the Android app could simply use the same id, but it seemed to me, that this would be fairly confusing. So I picked the id `com.hivewallet.hive.cordova` for the Android app.

I see three options:

1) Switch the iOS app to also use the id `com.hivewallet.hive.cordova`. I don't know if this is possible, as it might not be possible to change the app id in the app store.
2) Use Cordova's hook mechanism to trigger a change of the id, whenever the Android app is build. I attempted this once, but the resulting build was broken. I haven't looked further into it though, I still think it should be possible.
3) Leave the situation as it is, keep an Android branch where the id is changed and close this ticket. ;-)

**Comment by ghost** [comment]
Closing and opening a general issue about this here:

https://github.com/hivewallet/hive-js/issues/240
