### ISSUE TITLE
Synchronising wallet - takes 30 minutes

### ISSUE THREAD

**Issue by hughht5** [hivewallet/hive-ios#43]
My hive wallet is unusable as it takes anywhere between 5 and 30 minutes to synchronise. After I type in the pin is just sits there for ages. Any idea why?

**Comment by dabura667** [comment]
Do you have a lot of transaction history?

**Comment by hughht5** [comment]
No. It's got maybe 100 transactions maximum

**Comment by weilu** [comment]
Yeah, that's a lot of transactions for a web wallet. The best thing to do is to create a new wallet and transfer your funds over.

**Comment by hughht5** [comment]
I do that on my debit card every week. Is this problem solvable down the
line?

For now I'll make a new one.

On Monday, 2 February 2015, Wei Lu notifications@github.com wrote:

> Yeah, that's a lot of transactions for a web wallet. The best thing to do
> is to create a new wallet and transfer your funds over.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hivewallet/hive-ios/issues/43#issuecomment-72395828.

## 

Mr Hugh Halford-Thompson
+44 (0)7789231917

http://www.3distributed.com/

http://www.quickbitcoin.co.uk/

http://hughht5.blogspot.co.uk/ http://www.techcrunchlite.com/

Flat 2
Minus One House
Lyttleton Road
Leyton
E10 5NQ
UK

Too brief? Here's why! http://emailcharter.org

**Comment by weilu** [comment]
Yes, that's why we moved to use common-blockchain to talk to blockchain APIs. IIRC Helloblock already has support for querying with block height filtering. That would allow us to store some data locally and query for less data on login. 

Cheers
Wei

**Comment by ghost** [comment]
Closing this and other redundant issues now; #237 and #239 exist to consolidate. You guys may continue to comment here however.
