### ISSUE TITLE
Request: Expose xPub

### ISSUE THREAD

**Issue by pooleja** [hivewallet/hive-ios#46]
I am not sure if this is the correct place to request this...

Is there any support for exposing the xPub of the account in Hive?  Can this be added as a feature request?

We are working on an application that allows users to upload videos/content and get paid in bitcoins. To achieve this, we ask for the xPub of the user's wallet and then we generate "receive" addresses for the user, verify payments, etc. Then payments go directly into the user's wallet without us ever needing to hold their coins.

We are looking for a wallet that is cross platform we can work with, and Hive would be perfect if it supported this feature.

**Comment by weilu** [comment]
Related discussion: https://github.com/hivewallet/hive-js/issues/202

**Comment by ghost** [comment]
Closing for now, since we won't be addressing this for some time (if at all).
