### ISSUE TITLE
"Create new wallet" and "Open existing wallet" buttons don't do anything

### ISSUE THREAD

**Issue by jobukkit** [hivewallet/hive-ios#50]
When I press one of the two buttons, simply nothing happens. Tested on two devices. Latest iOS.

**Comment by ghost** [comment]
What is the latest iOS version in this case?

**Comment by dgiffin** [comment]
I have the same problem, iOS 8.4.1. I think it started after I pressed the open another wallet link

**Comment by jobukkit** [comment]
iOS 8.4.1 indeed

**Comment by ingria** [comment]
I had the same issue on iOS 8.4.1, but everything works fine on 9.0 (actually, not everything).

Had to be something with Safari renderer.

**Comment by ghost** [comment]
Hi guys,

Hive on iOS is basically dead. We don't have any developers with Macs anymore, so it's not really possible to keep it up-to-date or event o fix this problem. We're looking for another iOS maintainer, but until we do (and until we announce a new version!), you should be using something like Bread Wallet.

The good news is, your BIP32/BIP39 passphrases should be immediately portable.

**Comment by dgiffin** [comment]
A real shame, but these things happen  :-(

  David
