### ISSUE TITLE
Build Parameters

### ISSUE THREAD

**Issue by losh11** [hivewallet/hive-ios#53]
In the README file, to test something, you must use the production server. That requires modification so that the actual server needs to be connected.
I require the parameters that must be inputted for the test to work. Please don't post them on GitHub or openly (pretty sure you'll know that), if you could, for now if you have some sort of a testing server, can you give me the stuff I should put in the production config file? Preferably send to my email at loshan1212@gmail.com - to build to run on the App Store would mean that you either give me access to the parameters so I can connect to th database or you build the app yourself.

**Comment by losh11** [comment]
@w-hive going to create a pull request soon

**Comment by weilu** [comment]
What do you mean you must use production server? There's instruction in the readme on how to set up everything locally. You don't need any production credentials.
