### ISSUE TITLE
ETA on Test-flight beta?

### ISSUE THREAD

**Issue by dabura667** [hivewallet/hive-ios#6]
After trying to wrestle with virtual box and all various tools at my disposal, getting iOS to work for me has been a lot of work to no avail.

I think I will just wait until there is a version on Test-flight.

Just out of curiosity, what is a ballpark ETA for Test-flight beta?

**Comment by jenbennings** [comment]
@dabura667 Hopefully by the end of this week :)

**Comment by jenbennings** [comment]
Better late than never! Please put your details in issue #21 @dabura667.
